// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYZ9IIyyxCRuHsjpyjtZLobB_QK_UoKQ',
    appId: '1:187369178227:web:cd6ab854053438ba191606',
    messagingSenderId: '187369178227',
    projectId: 'gsg-flutter',
    authDomain: 'gsg-flutter.firebaseapp.com',
    storageBucket: 'gsg-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JaluHLl8JiSa9prICLku4kdCyiGRtvc',
    appId: '1:187369178227:android:90b5031ebeb04202191606',
    messagingSenderId: '187369178227',
    projectId: 'gsg-flutter',
    storageBucket: 'gsg-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWLW-OynXZjgZjzbyBEhCXe-z9jIbCz8',
    appId: '1:187369178227:ios:fcfdc2cc5f9aa834191606',
    messagingSenderId: '187369178227',
    projectId: 'gsg-flutter',
    storageBucket: 'gsg-flutter.firebasestorage.app',
    iosBundleId: 'com.example.gsgFlutter',
  );
}
